email:
  development:
    address: smtp.gmail.com
    port: 587
    domain: gmail.com
    user_name: twittwar95@gmail.com
    password: piave1915
  production:
    address:
    port:
    domain:
    user_name:
    password:

devise:
  development:
    mailer_sender: twittwar95@gmail.com
  production:
    mailer_sender: info@ragazzidel99.it

twitter:
  development:
    channel: LSETwistory
    consumer_key:
    consumer_secret:
    access_token:
    access_token_secret:
  production_italian:
    channel: lagrandeguerra
    consumer_key:
    consumer_secret:
    access_token:
    access_token_secret:
  production_english:
    channel: ww1fromitaly
    consumer_key:
    consumer_secret:
    access_token:
    access_token_secret:

facebook:
  development:
    app_secret:
    page_token:
  production_italian:
    app_secret:
    page_token:
  production_english:
    app_secret:
    page_token:

google:
  production:
    application_name:
    key:

airbrake:
  production:
    api_key:
